config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:destroy]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home/index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index,:edit,:update,:new,:create]
      resources :my_data, only: [:edit,:update]
    end

    resources :ad_detail, only: [:show, :create]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
  end

  devise_for :admins, :skip => [:registrations], controllers: { sessions: 'admins/sessions'}
  devise_for :members, controllers: { sessions: 'members/sessions',
                                      registrations: 'members/registrations'}

  root 'site/home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
  after_action :verify_authorized, only: [:new, :destroy]
  after_action :verify_policy_scoped, only: :index

  def index
    #@admins = Admin.all
    #@admins = Admin.where(role: 'full_access')
    
    #@admins = Admin.with_full_access
    #@admins = Admin.with_restricted_access

    @admins = policy_scope(Admin)
  end

  def new
    @admin = Admin.new
    authorize @admin
  end

  def create
    #@admin = AdminService.create(params_admin)
    @admin = Admin.new(params_admin)
    update_roles
    admin_name = @admin.name
    if @admin.save
      redirect_to backoffice_admins_path, notice: "O administrador (#{admin_name}) foi criado com sucesso."
    else
      render :new
    end
  end

  def edit
    # Uses before_action to set the admin
   # @admin = Admin.find(params[:id])
  end

  def update
    update_roles
    admin_name = @admin.name
    if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now #esse método para o servidor e envia um e-mail imediatamente
      redirect_to backoffice_admins_path, notice: "O administrador (#{admin_name}) foi atualizado com sucesso."
    else
      render :edit
    end
  end

  def destroy
    authorize @admin

    admin_name = @admin.name
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "O administrador (#{admin_name}) foi excluído com sucesso."
    else
      render :index
    end
  end


  private
    def remove_all_roles
      Role.availables.each do |role|
        @admin.remove_role(role)
      end
    end

    def update_roles
      remove_all_roles
      roles = params[:admin].extract!(:role_ids)

      roles[:role_ids].each do |role|
        if role != ""
          @admin.add_role(role)
        end
      end
    end

    def set_admin
      @admin = Admin.find(params[:id])
    end

    def params_admin
      if password_blank?
        params[:admin]= params[:admin].except(:password, :password_confirmation)
      end
  
      if @admin.blank?
        params.require(:admin).permit([:name, :email, :password, :password_confirmation])
      else
        params.require(:admin).permit(policy(@admin).permitted_attributes)
      end
    end

    def password_blank?
      params[:admin][:password].blank? &&
      params[:admin][:password_confirmation].blank?
    end
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:edit, :update]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    #@category = CategoryService.create(params_category)
    @category = Category.new(params_category)

    if @category.save
      redirect_to backoffice_categories_path, notice: "A categoria (#{@category.description}) foi criada com sucesso."
    else
      render :new
    end
  end

  def edit
    # Uses before_action to set the category
   # @category = Category.friendly.find(params[:id])
  end

  def update
    if @category.update(params_category)
      redirect_to backoffice_categories_path, notice: "A categoria (#{@category.description}) foi atualizada com sucesso."
    else
      render :edit
    end
  end

  def show
    @categories = Category.all
    respond_to do |format|
      format.html
      format.pdf do 
        render pdf: "categories"
      end
    end
  end

  private

    def set_category
      @category = Category.friendly.find(params[:id])
    end

    def params_category
      params.require(:category).permit(:description)
    end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController

  def index
    # renders app/views/backoffice/dashboard/index.html.erb
    @categories_groups = Category.all.collect { |c| [c.description, c.ads_count] }
  end
end

app/controllers/backoffice/diagrams_controller.rb
class Backoffice::DiagramsController < BackofficeController

    def index
        %x(bundle exec erd --filename='public/diagram')
    end
end

app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController

    def edit
        @admin = Admin.find(params[:id])
        
        #render partial: 'backoffice/admins/shared/send_mail', locals: {admin1: @admin} 
        #respond_to do |format|
        #    format.html
        #end
        
        #render create
        #link_to '#', class: "btn btn-info btn-circle", data: {toggle: 'modal', target: '#sendMailModal', admin2: admin}, onclick: "changeEmailField(\'#{admin.name}\',\'#{admin.email}\');"
        #redirect_to backoffice_admins_path
    end

    def create
        begin
            #  @admin = Admin.find(1)
            #  AdminMailer.update_email(current_admin, @admin).deliver_now
            @mgs_notify = "Mensagem enviada com sucesso para (#{params[:'recipient-text']})."
            AdminMailer.send_mail(current_admin, params[:'recipient-text'],params[:'subject-text'],params[:'message-text']).deliver_later #deliver_now para o servidor e envia imediatamente, deliver_later envia depois
        rescue
            @mgs_notify = "Não foi possivel enviar mensagem para (#{params[:'recipient-text']})."
        end
        redirect_to backoffice_admins_path, notice: @mgs_notify
    end

    def update
        
    end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout "backoffice"

    def pundit_user
      current_admin  # current_user for Pundit
    end
  end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
    OptionsForRoles = Struct.new(:id, :description)

    def options_for_roles
        Role::OPTIONS.map do |key, value|
            OptionsForRoles.new(key, value)
        end
    end
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/diagrams_helper.rb
module Backoffice::DiagramsHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/views/backoffice/admins/edit.html.erb
<%= render partial: "backoffice/admins/shared/form", locals: {action: "Editando Administrador"} %>

app/views/backoffice/admins/index.html.erb
<h1 class="page-header"><%= @admins.model_name.human(count: 2) %></h1>

    <div class="panel panel-default">
        <br>
        <div class="panel-heading">
            Administradores
            <% if policy(@admins).new? %>
                <%= link_to new_backoffice_admin_path, class: "btn btn-success btn-circle float-right", style: "margin-top:-5px" do %>
                    <i class="fa fa-link"></i>
                <% end %>
            <% end %>
        </div>
        <br>
        <!-- /.panel-heading -->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th><%= @admins.model.human_attribute_name('name')%></th>
                            <th><%= @admins.model.human_attribute_name('email')%></th>
                            <th><%= @admins.model.human_attribute_name('role')%></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @admins.each do |admin| %>
                        <tr>
                            <td><%= admin.id %></td>
                            <td><%= admin.name %></td>
                            <td><%= admin.email %></td>
                            <td><%= admin.roles_descriptions.join(', ') %></td>
                            <td style="width: 150px">
                                <!-- link_to '#', class: "btn btn-info btn-circle", data: {toggle: 'modal', target: '#sendMailModal'} do -->    
                                <!-- link_to edit_backoffice_send_mail_path(admin), class: "btn btn-info btn-circle", remote: true do -->  
                                <!-- link_to '#', class: "btn btn-info btn-circle", data: {toggle: 'modal', target: '#sendMailModal', admin2: admin}, onclick: "changeEmailField(\'#{admin.name}\',\'#{admin.email}\');" do -->  
                                
                                <%= link_to '#', class: "btn btn-info btn-circle", data: {toggle: 'modal', target: '#sendMailModal', admin2: admin}, onclick: "changeEmailField(\'#{admin.name}\',\'#{admin.email}\');" do %>    
                                    <i class="fa fa-envelope"></i>
                                    <% @admin1="#{admin.email}" %>
                                <% end %>
                                <%= link_to edit_backoffice_admin_path(admin), class: "btn btn-primary btn-circle" do %>    
                                    <i class="fa fa-edit"></i>
                                <% end %>

                                <% if current_admin.id != admin.id && policy(@admins).destroy? %>
                                    <% if policy(@admins).destroy? %>
                                        <%= link_to backoffice_admin_path(admin), method: :delete, class: "btn btn-danger btn-circle",
                                            data: {confirm: t('messages.confirm_with', item: admin.name)} do %>    
                                            <i class="fa fa-minus"></i>
                                        <% end %>
                                    <% else %>
                                        <%= link_to '#', class: "btn btn-danger btn-circle",
                                            data: {confirm: t('messages.not_authorized')} do %>    
                                            <i class="fa fa-minus"></i>
                                        <% end %>
                                    <% end %>
                                <% else %>
                                    <%= link_to '#', disable: "disable", class: "btn btn-danger btn-circle" do %>    
                                        <i class="fa fa-minus"></i>
                                    <% end %>
                                <% end %>
                            </td>
                        </tr>
                        <%= render partial: 'backoffice/admins/shared/send_mail' %>
                        <% end %>
                    </tbody>
                </table>
            </div>
            <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
    </div>    

    
    <script>
    function changeEmailField(nome,email){
        //$('#recipient-name2').text('Nova mensagem passra ')
        $("h4[id = sendMailModalLabel]").text("Nova mensagem para " + nome);
        $('#recipient-text').val(email)
       // $('#testeVini').attr('value',email)
    }
    </script>

app/views/backoffice/admins/new.html.erb
<%= render partial: "backoffice/admins/shared/form", locals: {action: "Novo Administrador"} %>