config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:destroy]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home/index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index,:edit,:update,:new,:create]
      resources :my_data, only: [:edit,:update]
    end

    resources :ad_detail, only: [:show, :create]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
  end

  devise_for :admins, :skip => [:registrations], controllers: { sessions: 'admins/sessions'}
  devise_for :members, controllers: { sessions: 'members/sessions',
                                      registrations: 'members/registrations'}

  root 'site/home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header"><%= "Administradores" %></h1>
<br>
<div class="panel panel-default">
    <br>
    <div class="panel-heading">
        <%= action %>
    </div><br>
    <% if @admin.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
            <% @admin.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>            
        </div>
    <% end %>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="col-lg-6">
            <%= form_for([:backoffice, @admin]) do |f| %>
                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: "form-control", placeholder: "Nome do administrador" %>
                </div>
                <div class="form-group">
                    <%= f.label :email %>
                    <%= f.text_field :email, class: "form-control", placeholder: "E-mail do administrador" %>
                </div>
                <% if policy(@admin).edit? %>
                    <div class="form-group">
                        <%= f.label :role %>
                        <!-- f.collection_radio_buttons :role, options_for_roles, :id, :description --> 
                        <%= f.collection_check_boxes(:role_ids, options_for_roles, :id, :description, checked: @admin.checked_roles) do |b| %>
                            <div class="radio">
                                <%= b.label { b.check_box + b.text } %>
                            </div>
                        <% end %>
                    </div>
                <% end %>
                <div class="form-group">
                    <%= f.label :password %>
                    <%= f.password_field :password, class: "form-control", placeholder: "Senha" %>
                </div>
                <div class="form-group">
                    <%= f.label :password_confirmation %>
                    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirmação da senha" %>                    
                </div>
                <br><button type="submit" class="btn btn-default">Salvar</button>
            <% end %>
        </div>
    </div>
    <!-- /.panel-body -->
</div>

app/views/backoffice/admins/shared/_send_mail.html.erb
<div class="modal" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="sendMailModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
          <h4 class="modal-title" id="sendMailModalLabel"><%= "Nova mensagem para #{@admin1}" %></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
            <!-- form_with url: backoffice_send_mail_index_path, method: :create do |f| -->
            <%= form_tag(backoffice_send_mail_index_path) do %>
                <div class="form-group">
                    <%= label_tag 'Para:' %>
                    <%= text_field_tag(:'recipient-text', nil, class: "form-control", readonly: "readonly", placeholder: "Informe o e-mail destinatário") %>
                </div>
                <div class="form-group">
                    <%= label_tag 'Assunto:' %>
                    <%= text_field_tag(:'subject-text', nil, class: "form-control", placeholder: "Informe o assunto") %>
                </div>
                <div class="form-group">
                    <%= label_tag 'Mensagem:' %>
                    <%= text_field_tag(:'message-text', nil, class: "form-control", placeholder: "Escreva uma mensagem") %>
                </div>
                <br>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
            <% end %>
      </div>
      
    </div>
  </div>
</div>