config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:destroy]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home/index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index,:edit,:update,:new,:create]
      resources :my_data, only: [:edit,:update]
    end

    resources :ad_detail, only: [:show, :create]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
  end

  devise_for :admins, :skip => [:registrations], controllers: { sessions: 'admins/sessions'}
  devise_for :members, controllers: { sessions: 'members/sessions',
                                      registrations: 'members/registrations'}

  root 'site/home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  # RatyRate Gem
  ratyrate_rater
  
  # Associations
  has_many :ads
  has_one :profile_member
  has_one :order
  accepts_nested_attributes_for :profile_member

  # Validations
  validate :nested_attributes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  
  def nested_attributes
    if nested_attributes_blank?
      errors.add(:base, "É necessário preencher os campos Nome e Sobrenome")
    end
  end

  def nested_attributes_blank?
    profile_member.name.blank? || profile_member.surname.blank?
  end
end

app/controllers/members/registrations_controller.rb
class Members::RegistrationsController < Devise::RegistrationsController
    before_action :configure_permitted_parameters

    def new
        build_resource({})
        resource.build_profile_member
        respond_with self.resource
    end

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :password, :password_confirmation, :profile_member_attributes => [:name, :surname]])
    end
end

app/controllers/members/sessions_controller.rb
class Members::SessionsController < Devise::SessionsController
    protected

    def after_sign_in_path_for(resource)
        stored_location = stored_location_for(resource)

        #if stored_location.match("site/ad_detail")
        #  stored_location
        #else
            site_profile_dashboard_index_path
        #end
    end

end

app/helpers/members/registrations_helper.rb
module Members::RegistrationsHelper
end

app/views/members/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <!--h2-->
      <!--%= I18n.t("errors.messages.not_saved", count: resource.errors.count, resource: resource.class.model_name.human.downcase) %-->
    <!--/h2-->
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Acessar", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>